export const actionTypes = {
    LAY_DANH_MUC_KHOA_HOC: 'LAY_DANH_MUC_KHOA_HOC',
    LAY_DANH_SACH_KHOA_HOC: 'LAY_DANH_SACH_KHOA_HOC',
    LAY_CHI_TIET_KHOA_HOC: 'LAY_CHI_TIET_KHOA_HOC',
    THEM_KHOA_HOC: 'THEM_KHOA_HOC',
    UPLOAD_HINH_ANH_KHOAHOC: 'UPLOAD_HINH_ANH_KHOAHOC',
    LAY_KHOA_HOC_THEO_DANH_MUC: 'LAY_KHOA_HOC_THEO_DANH_MUC',
    TIM_KIEM_KHOA_HOC: 'TIM_KIEM_KHOA_HOC',
    KHOA_HOC_CHUA_GHI_DANH: 'KHOA_HOC_CHUA_GHI_DANH',
    KHOA_HOC_CHO_XET: 'KHOA_HOC_CHO_XET',
    KHOA_HOC_DA_GHI_DANH: 'KHOA_HOC_DA_GHI_DANH',
}