export const actionTypes = {
    DANG_NHAP: 'DANG_NHAP',
    DANG_XUAT: 'DANG_XUAT',
    LAY_DANH_SACH_NGUOI_TAO: 'LAY_DANH_SACH_NGUOI_TAO',
    LAY_THONG_TIN_NGUOI_DUNG: 'LAY_THONG_TIN_NGUOI_DUNG',
    CAP_NHAT_NGUOI_DUNG: 'CAP_NHAT_NGUOI_DUNG',
    THEM_NGUOI_DUNG: 'THEM_NGUOI_DUNG',
    TIM_NGUOI_DUNG: 'TIM_NGUOI_DUNG',
    NGUOI_DUNG_CHUA_GHI_DANH: 'NGUOI_DUNG_CHUA_GHI_DANH',
    HOC_VIEN_DA_THAM_GIA_KHOA_HOC: 'HOC_VIEN_DA_THAM_GIA_KHOA_HOC',
    NGUOI_DUNG_CHO_DUYET: 'NGUOI_DUNG_CHO_DUYET',
}